version: 0.2

phases:
  pre_build:
    commands:
      - echo "=========================================="
      - echo "Stage 1: PRE-BUILD"
      - echo "=========================================="
      - echo "🔨 Iniciando build..."
      - echo "📅 Timestamp: $(date)"
      - echo ""
      - echo "🔑 Fazendo login no ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/seu-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "✅ Login bem-sucedido"
      - echo ""

  build:
    commands:
      - echo "=========================================="
      - echo "Stage 2: BUILD"
      - echo "=========================================="
      - echo ""
      - echo "🧪 Executando testes..."
      - pip install -r requirements.txt
      - pytest tests/ -v --cov=. --cov-report=xml
      - echo "✅ Testes passaram!"
      - echo ""
      - echo "🐳 Buildando imagem Docker..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "✅ Build completo"
      - echo ""

  post_build:
    commands:
      - echo "=========================================="
      - echo "Stage 3: POST-BUILD"
      - echo "=========================================="
      - echo ""
      - echo "📤 Fazendo push para ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "✅ Push para ECR completo"
      - echo ""
      - echo "📝 Gerando imagedefinitions.json..."
      - printf '[{"name":"seu-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo ""
      - echo "=========================================="
      - echo "✅ BUILD CONCLUÍDO COM SUCESSO!"
      - echo "=========================================="

artifacts:
  files:
    - imagedefinitions.json
  name: BuildArtifact

cache:
  paths:
    - "/root/.cache/pip/**/*"

reports:
  coverage:
    files:
      - coverage.xml
    file-format: "COBERTURAXML"
